### ISSUE TITLE
Issue with `timestep` setting in `wanda_config.yaml`

### ISSUE THREAD

**Issue by wjhvv** [ruchikachavhan/concept-prune#1]
Hello,

I encounter errors whenever I set the value of `timestep` in `wanda_config.yaml` to be smaller than 51. Is there a requirement that this value must be greater than 50? 

Thank you!

**Comment by ruchikachavhan** [comment]
Hi. Thank you for pointing out this error. It is because of one extra forward pass for unconditional output for classifier-free guidance which we also take into account. That is why the number of timesteps is 51 instead of 50. Thank you!
